#!/usr/bin/env python3
"""
tsx_wang_to_json.py  -  Turn a Tiled tileset's terrain ("wang") data into JSON
-----------------------------------------------------------------------------
WHAT:  LPC Revised tilesets ship Tiled .tsx files that say which tile fits
       which terrain transition (grass->water shore, fence corner, ...).
       This script extracts that into a small JSON lookup the game reads at
       runtime (realms/_shared/wang_autotiler.gd) to autotile maps from an
       ASCII layout. No Tiled needed at runtime.

OUTPUT (one JSON file):
  corner sets  key "tl,tr,br,bl"  (terrain name at each tile CORNER)
  edge sets    key "t,r,b,l"      (terrain name on each tile EDGE, "" = none)
  each key -> list of [tile_id, weight]  (several = random variants)
  plus tile_size / columns / image so tile ids map to atlas coordinates:
      atlas_x = id % columns,  atlas_y = id // columns
  animations: tile_id -> {"frames": n, "step": columns between frames,
      "ms": [duration per frame]}  for animated tiles used by the kept sets
      (only same-row, evenly spaced frames: the layout Godot atlases support).

USAGE:
  python3 tools/tiled/tsx_wang_to_json.py <tileset.tsx> <out.json> [--sets "Summer Terrain,Fences"]
  python3 tools/tiled/tsx_wang_to_json.py --help

Written with help from Claude (Anthropic) via Claude Code.
Made with love from your friendly hacker - er2oneousbit
"""
import argparse
import json
import sys
import xml.etree.ElementTree as ET


def parse_args():
    ap = argparse.ArgumentParser(
        description="Extract Tiled wangset (terrain) data from a .tsx into a JSON lookup for the game.",
        epilog="Example: python3 tools/tiled/tsx_wang_to_json.py lpc-tileset-terrain-summer.tsx data/tilesets/lpc_summer_wang.json --sets \"Summer Terrain,Fences\"")
    ap.add_argument("tsx", help="Tiled tileset file (.tsx)")
    ap.add_argument("out", help="output .json path")
    ap.add_argument("--sets", default="", help="comma-separated wangset names to keep (default: all)")
    ap.add_argument("--image", default="", help="override the image path stored in the JSON (res:// path)")
    ap.add_argument("--debug", action="store_true", help="print every key and its tiles")
    return ap.parse_args()


def main():
    args = parse_args()
    try:
        root = ET.parse(args.tsx).getroot()
    except (OSError, ET.ParseError) as e:
        sys.exit(f"ERROR: can't read {args.tsx}: {e}")

    # Per-tile probability (Tiled <tile probability="0.5">), default 1.
    weights = {int(t.get("id")): float(t.get("probability", "1")) for t in root.findall("tile")}
    image = root.find("image")
    keep = {s.strip() for s in args.sets.split(",") if s.strip()}

    out = {
        "_comment": f"Generated by tools/tiled/tsx_wang_to_json.py from {args.tsx.split('/')[-1]}. Do not edit by hand.",
        "image": args.image or (image.get("source") if image is not None else ""),
        "tile_size": int(root.get("tilewidth")),
        "columns": int(root.get("columns")),
        "corner_sets": {},
        "edge_sets": {},
        "animations": {},
    }
    columns = out["columns"]
    # Tiled <tile id="..."><animation><frame tileid="..." duration="ms"/>...
    tsx_anims = {}
    for t in root.findall("tile"):
        a = t.find("animation")
        if a is not None:
            tsx_anims[int(t.get("id"))] = [(int(f.get("tileid")), int(f.get("duration"))) for f in a.findall("frame")]

    found = []
    for ws in root.iter("wangset"):
        name = ws.get("name")
        found.append(name)
        if keep and name not in keep:
            continue
        colors = [c.get("name") for c in ws.findall("wangcolor")]
        kind = ws.get("type")
        table = {}
        for wt in ws.findall("wangtile"):
            w = [int(v) for v in wt.get("wangid").split(",")]
            names = ["" if i == 0 else colors[i - 1] for i in w]
            # Tiled wangid order: top, top-right, right, bottom-right,
            #                     bottom, bottom-left, left, top-left
            if kind == "corner":
                key = ",".join([names[7], names[1], names[3], names[5]])  # tl,tr,br,bl
            elif kind == "edge":
                key = ",".join([names[0], names[2], names[4], names[6]])  # t,r,b,l
            else:
                print(f"WARNING: skipping wangset '{name}' (type '{kind}' not supported)", file=sys.stderr)
                break
            tid = int(wt.get("tileid"))
            table.setdefault(key, []).append([tid, weights.get(tid, 1.0)])
        target = out["corner_sets"] if kind == "corner" else out["edge_sets"]
        target[name] = {"colors": colors, "tiles": table}
        print(f"{name}: {kind}, {len(colors)} terrains, {len(table)} combinations")
        if args.debug:
            for k, v in sorted(table.items()):
                print(f"   {k:60s} {v}")

    # Animations for tiles we actually use, when Godot's atlas can express them.
    used = {tid for sets in (out["corner_sets"], out["edge_sets"]) for ws in sets.values()
            for tiles in ws["tiles"].values() for tid, _w in tiles}
    skipped = 0
    for tid in sorted(used):
        frames = tsx_anims.get(tid)
        if not frames or len(frames) < 2:
            continue
        ids = [f[0] for f in frames]
        steps = {b - a for a, b in zip(ids, ids[1:])}
        same_row = len({i // columns for i in ids}) == 1
        if ids[0] != tid or len(steps) != 1 or not same_row or steps.pop() <= 0:
            skipped += 1
            continue
        out["animations"][str(tid)] = {"frames": len(ids), "step": ids[1] - ids[0], "ms": [f[1] for f in frames]}
    print(f"animations: {len(out['animations'])} kept, {skipped} skipped (layout Godot can't express)")

    missing = keep - set(found)
    if missing:
        sys.exit(f"ERROR: wangset(s) not found: {', '.join(sorted(missing))}. Available: {', '.join(found)}")

    with open(args.out, "w") as f:
        json.dump(out, f, indent=1)
        f.write("\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
